### PR TITLE
Bumping to 5.8.2

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Motivation:

using the latest of junit jupiter 
Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by matzew** [comment]
I've contributed to vert.x before: https://github.com/vert-x3/vertx-kafka-client/commits?author=matzew

**Comment by matzew** [comment]
I updated the commit, using my `Apache` email address - which I think I used for Eclipse (instead of my RHT one)

**Comment by matzew** [comment]
@vietj @jponge  any idea on this "ECA" thing? or mind to do the bump yourself

**Comment by jponge** [comment]
Most likely the Eclipse bot not recognising your email as that of an Eclipse Contributor.

You have 2 options:

create an Eclipse account if you don’t have one, and sign it, or
just consider that since you are a Red Hat employee you are already covered (perhaps signing your commits with your Red Hat email is best)

**Comment by matzew** [comment]
@jponge I have now signed it via the Red Hat Email. And I have done contributions to vert.x before (as a RHT employee), so I must be covered, one way or the other

**Review by jponge — APPROVED** [review]

**Comment by jponge** [comment]
Great!

**Comment by jponge** [comment]
I'll ignore that ECA check

**Pull request merged**
