### PR TITLE
Provide options for the Vertx JUnit runtime

### PR DESCRIPTION
**Pull request by Stwissel**
Motivation:
When running JUnit test with `@ExtendWith(VertxExtension.class)`, the Vert.x instance get created with default parameters. This makes debugging hard due to the blocking errors. The change proposed would look for an environment parameter **vertx.parameter.filename** and load it as JsonObject to populate the VertxOptions

### CODE REVIEW

**Comment by vietj** [comment]
I think it should be tested and documented.

**Comment by Stwissel** [comment]
@vietj -> Where's the documentation page, I can add a pull request there too!

**Comment by vietj** [comment]
you can find it here https://github.com/vert-x3/vertx-junit5/blob/master/src/main/asciidoc/index.adoc

**Comment by jponge** [comment]
I'll be tracking this

**Comment by thced** [comment]
I like this idea!
Would it be hard to wire up a VertxOptions class that could be used, like an extension? As an alternative to config file.

**Comment by Stwissel** [comment]
Added the update to the documentation page. Couldn't find the documentation that describes the exact Json format for VertxOptions. Any pointers?

**Comment by vietj** [comment]
@Stwissel can you look at the index.adoc file ?

**Comment by vietj** [comment]
can we get this done soon so it is merged in 4.0.3 ?

**Comment by jponge** [comment]
We also need tests

**Comment by vietj** [comment]
right.

**Comment by vietj** [comment]
@Stwissel ping

**Comment by Stwissel** [comment]
@vietj Pong

**Comment by Stwissel** [comment]
Success-full Test

**Comment by Stwissel** [comment]
Messed up my committer identities - closing this and reopen freshly

**Pull request closed without merging**
