### PR TITLE
Allow to pre-configure vertx instances with VertxExtension

### PR DESCRIPTION
**Pull request by u6f6o**
This pull request allows to pre-configure vertx instances before they'll be injected in test/setup/teardown methods.

Junit5 offers a `@RegisterExtension` annotation that allows to configure extension objects. More information can be found [here](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-programmatic). 

```
  @RegisterExtension
  private VertxExtension vertxExtension = new VertxExtension.Builder()
      .vertx(() -> Vertx.vertx(
        new VertxOptions()
          .setMetricsOptions(
            new MicrometerMetricsOptions()
              .setPrometheusOptions(new VertxPrometheusOptions().setEnabled(true))
              .setEnabled(true))))
      .build(); 
```

### CODE REVIEW

**Comment by jponge** [comment]
Thanks for your PR.

Would you have tests and documentation to support the change?

**Comment by u6f6o** [comment]
@jponge: Welcome. Sure, as soon as I find time I'll provide tests and documentation.

**Comment by u6f6o** [comment]
@jponge : sorry for, the delay, but I am struggling with an exception that occurs when I use the `@RegisterExtension` approach: 

```SEVERE: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@6fe7aac8
java.lang.UnsupportedOperationException
	at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.iterator(BaseMpscLinkedArrayQueue.java:201)
	at java.util.AbstractCollection.remove(AbstractCollection.java:282)
	at io.netty.util.concurrent.SingleThreadEventExecutor.removeTask(SingleThreadEventExecutor.java:340)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:781)```

This exception also occurs if I rollback to the commit before I introduced my changes. It also not quite reliable.

**Comment by u6f6o** [comment]
@jponge: the first try to provide a more flexible version of the VertxExtension looked quite promising, further investigation and tests revealed though, that it is not working as expected in all scenarios :-( I tried to dig deeper into the junit5 framework but gave up at some point since I am currently lacking the time. I would suggest to close the PR for now.

**Comment by jponge** [comment]
Ok thanks @u6f6o

**Pull request closed without merging**
